# Generated by Django 6.0 on 2026-01-28 00:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id_categoria', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('descripcion', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'in_categoria',
            },
        ),
        migrations.CreateModel(
            name='CodigoBarras',
            fields=[
                ('id_codigo', models.AutoField(primary_key=True, serialize=False)),
                ('codigo', models.CharField(blank=True, help_text='Escanea el código de barras aquí', max_length=50, null=True, unique=True)),
            ],
            options={
                'db_table': 'in_codigo_barras',
            },
        ),
        migrations.CreateModel(
            name='Estante',
            fields=[
                ('id_estante', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('cantidad_niveles', models.IntegerField(default=1, help_text='¿Cuántos niveles tiene este estante?', verbose_name='Cantidad de niveles')),
            ],
            options={
                'db_table': 'in_estante',
            },
        ),
        migrations.CreateModel(
            name='EntradaMercancia',
            fields=[
                ('id_entrada_mercancia', models.AutoField(primary_key=True, serialize=False)),
                ('unidades', models.IntegerField()),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('CodigoBarras', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='inventario.codigobarras')),
            ],
            options={
                'db_table': 'in_entrada_mercancia',
            },
        ),
        migrations.CreateModel(
            name='Nivel',
            fields=[
                ('id_nivel', models.AutoField(primary_key=True, serialize=False)),
                ('numero', models.IntegerField()),
                ('estante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.estante')),
            ],
            options={
                'db_table': 'in_nivel',
                'unique_together': {('numero', 'estante')},
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id_producto', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=255, unique=True, verbose_name='Descripción del Producto')),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('unidades_stock', models.IntegerField(default=0, help_text='Total de unidades (usado cuando no requiere lotes)')),
                ('unidades_en_exhibicion', models.IntegerField(default=0)),
                ('cantidad_max_exhibicion', models.IntegerField(default=1)),
                ('cantidad_min_exhibicion', models.IntegerField(default=1)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('requiere_lotes', models.BooleanField(default=True)),
                ('categoria', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='inventario.categoria')),
                ('nivel', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ubicacion', to='inventario.nivel')),
            ],
            options={
                'db_table': 'in_producto',
            },
        ),
        migrations.AddField(
            model_name='codigobarras',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='inventario.producto'),
        ),
        migrations.CreateModel(
            name='Lote',
            fields=[
                ('id_lote', models.AutoField(primary_key=True, serialize=False)),
                ('codigo', models.CharField(max_length=100)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('fecha_expedicion', models.DateField()),
                ('fecha_vencimiento', models.DateField()),
                ('cantidad_disponible', models.IntegerField()),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='inventario.producto')),
            ],
            options={
                'db_table': 'in_lote',
                'unique_together': {('producto', 'codigo', 'fecha_vencimiento')},
            },
        ),
    ]
