# Generated by Django 6.0 on 2025-12-31 18:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id_categoria', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'in_categoria',
            },
        ),
        migrations.CreateModel(
            name='Estante',
            fields=[
                ('id_estante', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'in_estante',
            },
        ),
        migrations.RenameField(
            model_name='producto',
            old_name='cantidad_en_stock',
            new_name='unidades',
        ),
        migrations.AddField(
            model_name='producto',
            name='id_categoria_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='inventario.categoria'),
        ),
        migrations.CreateModel(
            name='Nivel',
            fields=[
                ('id_nivel', models.AutoField(primary_key=True, serialize=False)),
                ('numero', models.IntegerField()),
                ('id_estante_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.estante')),
            ],
            options={
                'db_table': 'in_nivel',
                'unique_together': {('numero', 'id_estante_id')},
            },
        ),
        migrations.AddField(
            model_name='producto',
            name='id_nivel_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ubicacion', to='inventario.nivel'),
        ),
    ]
