# Generated by Django 6.0 on 2025-12-31 18:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0002_categoria_estante_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='nivel',
            old_name='id_estante_id',
            new_name='estante',
        ),
        migrations.RenameField(
            model_name='producto',
            old_name='id_categoria_id',
            new_name='categoria',
        ),
        migrations.RenameField(
            model_name='producto',
            old_name='id_nivel_id',
            new_name='nivel',
        ),
        migrations.AlterUniqueTogether(
            name='nivel',
            unique_together={('numero', 'estante')},
        ),
    ]
