# Generated by Django 6.0 on 2025-12-31 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0003_rename_id_estante_id_nivel_estante_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='producto',
            old_name='unidades',
            new_name='unidades_totales',
        ),
        migrations.AddField(
            model_name='estante',
            name='niveles_a_crear',
            field=models.IntegerField(default=1, help_text='¿Cuántos niveles tiene este estante?', verbose_name='Cantidad de niveles'),
        ),
        migrations.AddField(
            model_name='producto',
            name='cantidad_max_exhibicion',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='producto',
            name='cantidad_min_exhibicion',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='producto',
            name='unidades_en_exhibicion',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='categoria',
            name='nombre',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
