# Generated by Django 6.0 on 2025-12-31 19:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0004_rename_unidades_producto_unidades_totales_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='estante',
            old_name='niveles_a_crear',
            new_name='cantidad_niveles',
        ),
    ]
