# Generated by Django 6.0 on 2026-01-09 00:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0005_rename_niveles_a_crear_estante_cantidad_niveles'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='unidades_totales',
        ),
        migrations.AddField(
            model_name='producto',
            name='requiere_lotes',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='producto',
            name='unidades_stock',
            field=models.IntegerField(default=0, help_text='Total de unidades (usado cuando no requiere lotes)'),
        ),
        migrations.CreateModel(
            name='CodigoBarras',
            fields=[
                ('id_codigo', models.AutoField(primary_key=True, serialize=False)),
                ('codigo', models.CharField(max_length=100, unique=True)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='inventario.producto')),
            ],
            options={
                'db_table': 'in_codigo_barras',
            },
        ),
        migrations.CreateModel(
            name='Lote',
            fields=[
                ('id_lote', models.AutoField(primary_key=True, serialize=False)),
                ('codigo', models.CharField(max_length=100)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('fecha_expedicion', models.DateField()),
                ('fecha_vencimiento', models.DateField()),
                ('cantidad_disponible', models.IntegerField()),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='inventario.producto')),
            ],
            options={
                'db_table': 'in_lote',
                'unique_together': {('producto', 'codigo', 'fecha_vencimiento')},
            },
        ),
    ]
