# Generated by Django 6.0 on 2026-01-10 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0006_remove_producto_unidades_totales_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='descripcion',
            field=models.CharField(max_length=255, unique=True, verbose_name='Descripción del Producto'),
        ),
    ]
