# Generated by Django 6.0 on 2026-01-10 21:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0007_alter_producto_descripcion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='codigobarras',
            name='codigo',
            field=models.CharField(blank=True, help_text='Escanea el código de barras aquí', max_length=50, null=True, unique=True),
        ),
        migrations.CreateModel(
            name='EntradaMercancia',
            fields=[
                ('id_entrada_mercancia', models.AutoField(primary_key=True, serialize=False)),
                ('unidades', models.IntegerField()),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('CodigoBarras', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='inventario.codigobarras')),
            ],
            options={
                'db_table': 'in_entrada_mercancia',
            },
        ),
    ]
