# Generated by Django 6.0 on 2026-01-15 00:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Moneda',
            fields=[
                ('id_moneda', models.AutoField(primary_key=True, serialize=False)),
                ('codigo', models.CharField(max_length=10, unique=True)),
                ('nombre', models.CharField(max_length=100)),
                ('simbolo', models.CharField(blank=True, max_length=10, null=True)),
            ],
            options={
                'db_table': 'co_moneda',
            },
        ),
        migrations.CreateModel(
            name='TasaCambio',
            fields=[
                ('id_tasa_cambio', models.AutoField(primary_key=True, serialize=False)),
                ('tasa', models.DecimalField(decimal_places=4, max_digits=10)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('moneda', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='configuracion.moneda')),
            ],
            options={
                'db_table': 'co_tasa_cambio',
            },
        ),
    ]
