# Generated by Django 6.0 on 2026-01-28 00:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='detallecredito',
            table='ve_detalle_credito',
        ),
    ]
