# Generated by Django 6.0 on 2026-01-16 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0002_cliente_apellido_alter_cliente_nombre_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='metodopago',
            name='descripcion',
        ),
        migrations.AlterField(
            model_name='cliente',
            name='direccion',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='metodopago',
            name='nombre',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
