# Generated by Django 6.0 on 2026-01-16 23:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0003_remove_metodopago_descripcion_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='detalleventa',
            table='ve_detalle_venta',
        ),
    ]
