# Generated by Django 6.0 on 2026-01-17 18:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0005_estadoventa'),
    ]

    operations = [
        migrations.AddField(
            model_name='venta',
            name='estado',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='ventas.estadoventa'),
            preserve_default=False,
        ),
    ]
